// src/styles/styles.js
const styles = {
  app: {
    fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Arial, sans-serif',
    minHeight: "100vh",
    background: "linear-gradient(135deg, #0f0f0f 0%, #1a1a2e 50%, #16213e 100%)",
    color: "#fff",
  },
  header: {
    background: "rgba(26,26,46,0.95)",
    padding: "1rem 2rem",
    position: "sticky",
    top: 0,
    zIndex: 100,
  },
  headerContent: {
    maxWidth: 1400,
    margin: "0 auto",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 16,
  },
  logo: { display: "flex", alignItems: "center", gap: 10, cursor: "pointer" },
  logoText: { fontSize: "1.3rem", fontWeight: 700, color: "#fff" },
  nav: { display: "flex", gap: 20, justifyContent: "center", flex: 1 },
  navBtn: { background: "none", border: "none", color: "#cfcfcf", cursor: "pointer", fontSize: 15 },
  accountBtn: { display: "flex", gap: 8, alignItems: "center", cursor: "pointer" },
  pageContainer: {
    maxWidth: 1400,
    margin: "2rem auto",
    display: "grid",
    gridTemplateColumns: "1fr 320px",
    gap: "2rem",
    padding: "0 1rem",
    alignItems: "start",
  },
  homeHero: { minHeight: "60vh", display: "flex", alignItems: "center" },
  heroContainer: { width: "100%", maxWidth: 980 },
  heroWelcome: { fontSize: 28, margin: 0, fontWeight: 700 },
  heroSubtitle: { marginTop: 8, marginBottom: 10, color: "rgba(255,255,255,0.9)" },

  searchContainer: { display: "flex", gap: 12, alignItems: "center", marginTop: 12 },
  searchInput: {
    flex: 1,
    minWidth: 0,
    padding: "14px 16px",
    borderRadius: 14,
    border: "1px solid rgba(255,255,255,0.06)",
    background: "rgba(255,255,255,0.03)",
    color: "#fff",
    fontSize: 15,
  },
  searchBtn: {
    padding: 12,
    borderRadius: 12,
    border: "none",
    background: "linear-gradient(135deg,#667eea,#764ba2)",
    cursor: "pointer",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    minWidth: 56,
    height: 56,
    boxShadow: "0 6px 18px rgba(102,126,234,0.25)",
  },

  sidebar: { position: "sticky", top: 100 },
  sidebarSection: { background: "rgba(255,255,255,0.03)", padding: 14, marginBottom: 12, borderRadius: 10 },
  sidebarTitle: { color: "#cfcfcf", marginBottom: 8, fontSize: 13 },
  topicItem: { padding: 8, color: "#fff", borderBottom: "1px solid rgba(255,255,255,0.03)" },
  quickNoteItem: { padding: 10, background: "rgba(255,255,255,0.03)", borderRadius: 8, color: "#fff" },

  pageHeading: { fontSize: 26, marginBottom: 12, fontWeight: 700 },
  notesGrid: { display: "grid", gap: 12, gridTemplateColumns: "repeat(auto-fill, minmax(260px, 1fr))" },
  noteCard: { background: "rgba(255,255,255,0.03)", padding: 16, borderRadius: 12 },
  noteTitle: { fontSize: 16, margin: 0, fontWeight: 700, color: "#fff" },
  noteContent: { color: "#ddd", marginTop: 8 },

  noteActions: { display: "flex", gap: 8, marginTop: 10, alignItems: "center" },

  iconBtn: {
    padding: 8,
    borderRadius: 8,
    background: "linear-gradient(180deg, rgba(255,255,255,0.06), rgba(255,255,255,0.03))",
    border: "1px solid rgba(255,255,255,0.06)",
    cursor: "pointer",
    color: "#fff",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    boxShadow: "0 3px 10px rgba(0,0,0,0.25)",
  },

  showBtn: {
    padding: "8px 12px",
    borderRadius: 8,
    background: "#fff",
    border: "1px solid rgba(0,0,0,0.08)",
    color: "#111",
    cursor: "pointer",
    fontWeight: 600,
  },

  primaryBtn: {
    padding: "10px 14px",
    borderRadius: 12,
    background: "linear-gradient(135deg,#667eea,#764ba2)",
    border: "none",
    color: "#fff",
    cursor: "pointer",
  },

  secondaryBtn: {
    padding: "10px 14px",
    borderRadius: 12,
    background: "linear-gradient(135deg,#f093fb,#f5576c)",
    border: "none",
    color: "#fff",
    cursor: "pointer",
  },

  practiceGrid: { display: "grid", gap: 12 },
  optionBtn: {
    display: "block",
    width: "100%",
    padding: "14px 16px",
    borderRadius: 12,
    background: "rgba(255,255,255,0.03)",
    border: "1px solid rgba(255,255,255,0.04)",
    color: "#fff",
    cursor: "pointer",
    textAlign: "center",
    marginTop: 8,
  },

  selectedOption: { borderColor: "#667eea", background: "rgba(102,126,234,0.1)" },
  correctOption: { borderColor: "#4ade80", background: "rgba(74,222,128,0.08)" },

  modalOverlay: { position: "fixed", inset: 0, background: "rgba(0,0,0,0.5)", display: "flex", alignItems: "center", justifyContent: "center", zIndex: 3000 },
  modal: { width: "92%", maxWidth: 720, background: "#fff", color: "#111", borderRadius: 12, padding: 18 },
  modalTitle: { fontSize: 18, marginBottom: 10, fontWeight: 700 },
  modalInput: { width: "100%", padding: 10, borderRadius: 8, border: "1px solid #ccc", marginBottom: 10 },
  modalTextarea: { width: "100%", padding: 10, borderRadius: 8, border: "1px solid #ccc", minHeight: 140 },
  modalActions: { display: "flex", justifyContent: "flex-end", gap: 10, marginTop: 12 },

  statsGrid: { display: "grid", gridTemplateColumns: "repeat(auto-fit,minmax(180px,1fr))", gap: 12 },
  statCard: { background: "rgba(255,255,255,0.03)", padding: 12, borderRadius: 10, textAlign: "center" },
  statLabel: { color: "#cfcfcf", marginBottom: 6 },
  statNumber: { color: "#667eea", fontSize: 22, fontWeight: 700 },
};

export default styles;
